repos:
  - repo: local
    hooks:
      - id: lint
        name: ESLint
        entry: npm run lint
        language: system
        files: \.(js)$
        
      - id: format-check
        name: Prettier Format Check
        entry: npm run format:check
        language: system
        files: \.(js|css|html)$
        
      - id: test
        name: Run Tests
        entry: npm test
        language: system
        pass_filenames: false